import Head from "next/head";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <nav className={`${styles.Navbar}`}>
        <div className={`${styles.NavbarInner}`}>
          <div className={`${styles.LogoText}`}>LogoText</div>
          <div className={`${styles.NavlistWrapper}`}>
            <ul className={`${styles.Navlist}`}>
              <li className={`${styles.NavItem}`}>
                <a href='#projects'>Work</a>
              </li>
              <li className={`${styles.NavItem}`}>
                <a href='#about'>About</a>
              </li>
              <li className={`${styles.NavItem}`}>
                <a href='#contact'>Contact</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <main className={styles.Main}>
        <div className={`${styles.MainInner}`}>
          <div className={`${styles.HeroText}`}>
            We create <span>textwillchange.</span>
          </div>
        </div>
      </main>

      <section id='projects' className={styles.Projects}>
        <div className={`${styles.ProjectsInner}`}>
          <div className={`${styles.GridItem}`}></div>
          <div className={`${styles.GridItem}`}></div>
          <div className={`${styles.GridItem}`}></div>
          <div className={`${styles.GridItem}`}></div>
        </div>
      </section>

      <section id='about' className={`${styles.AboutBlurb}`}>
        <div className={`${styles.AboutBlurbInner}`}>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe et
            libero amet rerum, animi repellat dolores similique accusamus.
            Repellendus cupiditate ex commodi, libero provident voluptatum!
            Magnam reprehenderit delectus amet, exercitationem explicabo, id
            distinctio culpa quod quis quae quisquam. Rem saepe adipisci enim
            asperiores quos esse ab accusamus quam commodi dolorum.
          </p>
        </div>
      </section>

      <footer id='contact'>
        <div className={`${styles.FooterInner}`}>
          <a href=''>email@email.com</a>
          <p>Address 123, 123 StreetName Street</p>
          <p>City</p>
          &#169; Company 2022
        </div>
      </footer>
    </div>
  );
}
