import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.scss";

export default function Home() {
  const router = useRouter();

  return (
    <div className={`${styles.container} `}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <section className={styles.Main}>
        <div className={`${styles.MainInner} fade-in`}>
          <div className={`${styles.HeroText} `}>
            We create <span className={styles.TypeText}>textwillchange.</span>
          </div>
        </div>
      </section>

      <section id='projects' className={styles.Projects}>
        <div className={`${styles.ProjectsInner} fade-in`}>
          <div className={`${styles.GridItem} fade-in`}></div>
          <div className={`${styles.GridItem} fade-in`}></div>
          <div className={`${styles.GridItem} fade-in`}></div>
          <div className={`${styles.GridItem} fade-in`}></div>
        </div>
      </section>

      <section id='about' className={`${styles.AboutBlurb}`}>
        <div className={`${styles.AboutBlurbInner} fade-in`}>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe et
            libero amet rerum, animi repellat dolores similique accusamus.
            Repellendus cupiditate ex commodi, libero provident voluptatum!
            Magnam reprehenderit delectus amet, exercitationem explicabo, id
            distinctio culpa quod quis quae quisquam. Rem saepe adipisci enim
            asperiores quos esse ab accusamus quam commodi dolorum.
          </p>
        </div>
      </section>
    </div>
  );
}
